# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: XcodeSimulators@5
  inputs:
    actions: 'build'
    sdk: 'appletvos'
    packageApp: false
    destinationPlatformOption: 'tvOS'
    destinationSimulators: 'Apple TV 4K,OS=13.4'